### ISSUE TITLE
CR Touch support

### ISSUE THREAD

**Issue by jon-harper** [jon-harper/E34M1#1]
Pending fit testing. **ON HOLD** for redesign.

## CR Touch BOM

| Part | Qty |
|---|---|
| [cr_touch_mount.stl](https://github.com/jon-harper/E34M1/blob/testing/STL/abl/cr_touch_mount.stl) | 1 |
| Heat Set Insert, M3x5x4 | 2 |
| M3 x 6mm SHCS | 4 |

**Comment by jon-harper** [comment]
Discord report that this touches the horns. I'll move it out 1mm.

**Comment by jon-harper** [comment]
New revision up.

**Comment by InfinitiVoid** [comment]
![20230913_133302](https://github.com/jon-harper/E34M1/assets/75672431/c64202f2-bc73-4975-8efe-06d58c7f2112)
The new revision of CRTouch fits, works as intended.

X-offset: 41mm
Y-offset: 2mm

(offsets works for me, probably needs indepth calibration but I am too stupid for that)

**Comment by jon-harper** [comment]
I appreciate it. I haven't closed this--but forgot to notate--that the mounting arm slightly angles the CR Touch towards the nozzle. I think this is an artifact of ABS shrinkage, but have not yet resolved it.

**Comment by InfinitiVoid** [comment]
Yea, I noticed, this is the second one I printed. ASA with a 10mm brim and good supports works fine for me

**Comment by jon-harper** [comment]
Closing this, as there is a new CR Touch mount with Release 2.
