### ISSUE TITLE
Top modification for sensorless homing

### ISSUE THREAD

**Issue by RodentVienna** [jon-harper/E34M1#15]
Hi Jon,

would you be interested in officially supporting sensorless Homing for X by providing another TOP part without compartments for microswitched?

Thank you!
Best, Alex

**Comment by jon-harper** [comment]
The space for the limit switch can be left empty if you want to use sensorless homing.

I've seen [a modification on Printables](https://www.printables.com/model/333807-eva-3-sensor-less-homing-top-for-mgn9) that adds extra zip tie anchors where the X limit switch normally goes. Is this similar to what you're thinking?

**Comment by RodentVienna** [comment]
Hi Jon, thank you for your support! 
Yes, this is it, but for mgn9h instead of mgn12h.
I looked up printables.com, found 2 models for mgn12h, both without the mirrored zip-tie mount compartments. Having such as "official" alternative part from your project would be awesome. But i'd understand it will end up for you in "one more part to think of and support".
I guess i am fine with grabbing one of those mgn12h adaptions on printables, cut it in half, mirror the duplicated ziptie half and merge them back to a solid piece. Thank you!

**Comment by jon-harper** [comment]
E34M1 is generally only compatible with EVA 3 hotends and drives. If your build is going to be compatible with E34M1, start with the [/CAD/Top](https://github.com/jon-harper/E34M1/tree/main/CAD/top) folder. I've updated the files there with the latest for you.

Part of the reason I'm hesitant to implement this is that the halves of the E34M1 Top piece are not symmetrical, so it would take more work to implement than cut-and-mirror.

The wire anchor is also next to the X limit switch mount and would have to be removed, as well. See below for a visual:

![image](https://github.com/jon-harper/E34M1/assets/11852387/0c87bb4f-485e-47bc-9280-4cf923cb1b08)

**Comment by jon-harper** [comment]
I pinged you in Discord, but I've added this.

https://github.com/jon-harper/E34M1/blob/main/STL/top/top_no_endstop.stl
