### ISSUE TITLE
Orbiter 2 does not have space for lock washers

### ISSUE THREAD

**Issue by jon-harper** [jon-harper/E34M1#31]
I missed this modification to the original; while I'm at it, should check the others for the same mistake.

**Comment by zephyr2206** [comment]
What is this modification? Will the Orbiter 2 work with the heat inserts? Not sure what lock washers this is about.

**Comment by jon-harper** [comment]
> What is this modification? Will the Orbiter 2 work with the heat inserts? Not sure what lock washers this is about.

If you aren't using lock washers, the Orbiter 2 drive module will work without a problem. I believe this is also fixed and I simply forgot to close the issue.
