### ISSUE TITLE
Owleyes rear inlet fix. STL and STEP enclosed

### ISSUE THREAD

**Issue by 53Aries** [jon-harper/E34M1#45]
Made some adjustments to the owleyes to hopefully let air move more freely to all the ducts. 
Before:
![Screenshot 2024-12-29 225224](https://github.com/user-attachments/assets/b3e908a1-21c2-4856-8373-d4021bef4864)
After:
![Screenshot 2024-12-29 230221](https://github.com/user-attachments/assets/e7476059-4206-4057-8510-a67b7eee6be2)
[rear_dual_5015_owl_eyes_fixed.zip](https://github.com/user-attachments/files/18273424/rear_dual_5015_owl_eyes_fixed.zip)

**Comment by jon-harper** [comment]
I appreciate the contribution, but without a CFD analysis, there's not a good way to tell which version will be more efficient. Your version has increased volume, but may cost in terms of added turbulence from the screw bypasses.

There is probably a very good compromise between the two with a thinner "rib" below the screw holes, but at the moment I can't justify choosing one or the other.
