### ISSUE TITLE
Drive modules need BOM and fit testing

### ISSUE THREAD

**Issue by jon-harper** [jon-harper/E34M1#5]
There are drive modules in the `testing` branch that need fit testing. Please let me know here if you've tried one out.

Drives remaining to test:

- LGX
- ~~Orbiter 1.5~~
- ~~BMG~~
- ~~Orbiter 2.0~~
- ~~LGX Lite~~

**Comment by k-piekarczyk** [comment]
I can test the Orbiter 2.0 one next week when I have some more free time.

**Comment by jon-harper** [comment]
> I can test the Orbiter 2.0 one next week when I have some more free time.

Awesome, thank you!

**Comment by ratheon2474** [comment]
I can confirm the LGX Lite mount works

**Comment by k-piekarczyk** [comment]
The Orbiter 2.0 seems to be working fine as well 😄
