### ISSUE TITLE
Dual 5015 Rear Intake Fit Testing

### ISSUE THREAD

**Issue by jon-harper** [jon-harper/E34M1#7]
There's a new, dual-5015 radial fan rear intake. It's modified from a stock EVA 3 "cooling inlet" to E34M1-style with screw holes for the 4x 45mm screws that hold the Core together.

![image](https://user-images.githubusercontent.com/11852387/233857559-da893aa5-2adf-41fc-8f2b-c1f9fc2ea6d1.png)

![image](https://user-images.githubusercontent.com/11852387/233857578-a40e04f6-15af-4b0c-b83e-4d7f44d135cf.png)

## Bill of Materials

| Parts | Qty |
|---|---|
| [`dual_5015_inlet.stl`](https://github.com/jon-harper/E34M1/blob/testing/STL/rear/dual_5015_inlet.stl) | 1 |
| 5015 radial fan | 2 |
| M3 x 45 SHCS | 4 |
| M3 x 6mm SHCS | 1 |
| Lock washer, M3 | 5 |
| M3 x 20mm SHCS | 2 |
| Heat set inserts, M3x5x4 | 2 |

**Comment by sylwester-** [comment]
printed it yesterday. fits well, works well!

**Comment by jon-harper** [comment]
Thanks @sylwester- !
